name: Build CI/CD debs
on: [push, pull_request]

# Build .deb packages as needed
# publish them on S3-backed archive

jobs:
  build:
    name: Build debs
    runs-on: ubuntu-latest
    container: debian:10
    steps:
      - name: Use backport to work around checkout
        run: |
          cat > /etc/apt/sources.list.d/bp.list <<EOF
          deb http://deb.debian.org/debian buster-backports main
          EOF
      - name: Update
        run: apt-get update -q
      - name: Install deps
        run: |
          apt-get install -y --no-install-recommends ca-certificates
          apt-get install -y --no-install-recommends -t buster-backports git
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: identify merge-base commit
        run: git merge-base remotes/origin/master HEAD
      - name: Install deps
        run: apt-get install -y --no-install-recommends git python3 python3-requests python3-gnupg
      - name: Build
        run: cd $GITHUB_WORKSPACE && git status && ./.circleci/debops-ci --show-commands ci
        env:
          DEB_GPG_KEY: ${{ secrets.DEB_GPG_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
